language: go
go: 1.14.x
os: linux
dist: xenial

services:
  - docker

jobs:
  include:
    - stage: deploy
      name: Docker Image Build & Deploy
      if: tag IS present
      deploy:
        provider: script
        script: .travis/build-and-push.sh
        skip_cleanup: true
        on:
          tags: true