apiVersion: v1
kind: ConfigMap
metadata:
  name: ibm-cloud-module-provisioner-configmap
  namespace: ibm-cloud-module-provisioner-ocp-ns
  labels:
    app: ibm-cloud-module-provisioner-application
    subname: configmap
type: Opaque
data:
  test.test1: a
  test.test2: b
---
